# Use the 'slim' base for better compatibility with native modules
FROM node:20-slim

# Install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

# Layer Caching: Only install dependencies if they change
# This keeps the 'make re' cycle fast.
COPY package.json pnpm-lock.yaml ./

# We install ALL dependencies (including devDependencies like Vite/Vue-server-renderer)
# Note: We do NOT use --frozen-lockfile here so you can add packages as you develop.
RUN pnpm install
# COPY . .

ARG UID=1000
ARG GID=1000
RUN chown -R ${UID}:${GID} /app/node_modules 
RUN chown -R ${UID}:${GID} /app
# make the user own node modules (permissions on Linux)

COPY docker-entrypoint-dev.sh /usr/local/bin/docker-entrypoint-dev.sh
RUN chmod +x /usr/local/bin/docker-entrypoint-dev.sh

# Port for the SSR server
EXPOSE 3000

ENTRYPOINT ["/usr/local/bin/docker-entrypoint-dev.sh"]
CMD ["pnpm", "run", "dev"]