server {
    listen 80;

    # API routes (specific)
    location /api/notes {
        proxy_pass http://notes:3003;
    }

    # location /api/auth {
    #     proxy_pass http://auth:3001;
    # }

    # Frontend catch-all
    location / {
        proxy_pass http://frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}

server {
    location /api {
        proxy_pass http://gateway:8001;
    }

    listen 81;
    location / { 
		root /var/www/html;
		index index.html;
	}
}

server {
    listen 82;

    # everything goes through the api gateway
    location / {
        proxy_pass http://gateway:8001;
    }
}

server {
    listen 83;

    # API routes (specific)
    location /api/notes {
        proxy_pass http://notes:3003;
    }

    location /api/auth {
        proxy_pass http://auth:3000;
    }

    # Frontend catch-all
    location / {
        proxy_pass http://frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # X-User-ID: 42
    # X-User-Role: admin
    # X-User-Status: active
}