server {
    listen 80;

    resolver 127.0.0.11 valid=10s;

    # API routes (specific)
    location /api/notes {
        proxy_pass http://notes:3003;
    }

    location /api/auth {
        set $auth_upstream auth:3000;

        rewrite ^/api/auth/(.*) /$1 break;
        proxy_pass http://$auth_upstream;

        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    }

    # Frontend server
    location / {
        set $frontend_upstream frontend:3000;
        proxy_pass http://$frontend_upstream;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # X-User-ID: 42
    # X-User-Role: admin
    # X-User-Status: active
}

server {
    location /api {
        proxy_pass http://gateway:8001;
    }

    listen 81;
    location / { 
		root /var/www/html;
		index index.html;
	}
}

# server {
#     listen 82;

#     # everything goes through the api gateway
#     location / {
#         proxy_pass http://gateway:8001;
#     }
# }
