services:
  notes:
    build:
      context: ./requirements/notes
      dockerfile: Dockerfile
    image: notes
    container_name: notes
    restart: always
    networks:
      - transcendence

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    restart: always
    networks:
      - transcendence
    ports:
      - "0.0.0.0:8080:80"

  postgres:
    build: ./requirements/postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge

volumes:
  postgres_data: