// Still a bit confusing, might use later
// import { relations } from "drizzle-orm";

// Types in Postgres DB
import { PgTable,  } from "drizzle-orm/pg-core";

// Very cool: figures out the typescript "type" of a schema, Selecct for reading, Insert for creationg (field like ID which are generated by the DB may not exist)
import { InferSelectModel, InferInsertModel } from "drizzle-orm";


