[package]
name = "notes-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres"] }
tokio = { version = "1.49.0", features = ["full"] }
yrs = "0.18"           
uuid = { version = "1.0", features = ["v4", "serde"] }
tokio-tungstenite = "0.21" 